### ISSUE TITLE
Progessbar

### ISSUE THREAD

**Issue by saddy001** [zeehio/parmap#12]
Some kind of on-demand progress bar would be nice.

**Comment by zeehio** [comment]
Already done:

1. Install the optional dependency `pip install tqdm`
2.  `parmap.map(...,parmap_progress=True)`

**Comment by saddy001** [comment]
Oh I see. I was using an old parmap version from pip und missing tqdm. 
Then - why hiding great features? It should be mentioned on the entry page.

**Comment by zeehio** [comment]
Readme updated! Thanks for the suggestion!

The keyword argument support mentioned in the README is only available in GitHub (not yet on pypi). I plan to do a release one of these days, just write here if you want to use it and I will push to upload it sooner.
