### ISSUE TITLE
Progress bar for asynchronous methods

### ISSUE THREAD

**Issue by RealPolitiX** [zeehio/parmap#23]
The ``parmap.map_async`` and ``parmap.starmap_async`` methods have no option to display a progress bar. How to implement a progress bar on these methods?

**Comment by zeehio** [comment]
Since both functions are asynchronous you get a result object before the computation is finished.

It is up to you to manage the result object at that point. You could print anything in your code while the computation is going on and that would interfere with the progress bar printed by parmap. For that reason I did not offer the possibility of showing the progress bar.

parmap uses an internal property of the [AsyncResult](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.AsyncResult) object called  `_number_left` to know how many tasks are left. You may want to use that property as well. You may want to check how that is implemented in parmap: https://github.com/zeehio/parmap/blob/5b71945d44a3ba3fdf512d01368e77230f13ab65/parmap/parmap.py#L136

**Comment by RealPolitiX** [comment]
Thanks for your suggestion @zeehio, I looked at the function you mentioned. However, I think now that ``AsyncResult`` class has been merged with ``ApplyResult`` class in multiprocessing, right (see https://github.com/python/cpython/blob/master/Lib/multiprocessing/pool.py)? This makes the ``_number_left`` attribute disappear..

**Comment by zeehio** [comment]
Have you actually tested that or is it just your guess reading the code?

**Comment by zeehio** [comment]
I added continuous integration using the python nightly builds and parmap seems to keep working. If the parmap progress bar does not work for you in the development version of python as you suggested please confirm that to me and then I will do further tests.

It is not clear to me from your message if that is actually an issue and I don't want to spend time on testing an issue that may not exist.

Thanks for your feedback

**Comment by RealPolitiX** [comment]
Sorry, I have an upcoming deadline, so I haven't been writing here often. I can respond more frequently afterwards. I like your package very much, thanks for the effort! I used ``parmap`` [here](https://github.com/mpes-kit/pesfit/blob/master/pesfit/fitter.py) in the method ``parallel_fit()``. The version online is the working.

Initially, I was trying to figure out if there's a concrete speed increase between ``parmap.starmap()`` and ``parmap.starmap_async()``, but looks like not to me so far. Intuitively, I would think the asynchronous method can manage time better via load balancing, no? It turns out that after tuning ``chunksize`` and potentially the number of processes, the performances of the two methods are indistinguishable.

After reading your code, I tried to implement a progress bar for asynchronous method, something like the following,
```python
procs = parmap.starmap_async(func, args, **kwargs)

try:
    parmap.parmap._do_pbar(procs)
finally:
    results = procs.get()
```
This will run, but the progress bar never updated. So copied some parts of the ``_do_pbar()`` function out. This is when I realized the problem, the ``try`` part always fails, so it went into the ``finally`` part within ``_do_pbar()``. When I try to put the following code block into ``_do_pbar()``
```python
remaining = xxx
done_now = 0
with tqdm.tqdm(total=nspec) as pb:
    while done_now < xxx:
        print(done_now)
        print(fit_procs._job)
        
        if fit_procs.ready():
            print('Ready!')
            fit_results = fit_procs.get()
            pb.update(remaining)
            break
        
        print('Remaining = {}'.format(remaining))
        remaining_now = fit_procs._number_left*chunk_size
        done_now = remaining - remaining_now
        remaining = remaining_now
        pb.update(done_now)
            
        fit_procs.wait(2)
```
I got an error message that
```bash
AttributeError: '_ParallelAsyncResult' object has no attribute '_number_left'
```
Then I also checked the superclass of ``_ParallelAsyncResult`` to find out the info I described above. I'm using python version 3.6.4.

**Comment by zeehio** [comment]
Now I understood the issue and could reproduce it. Thanks.

Could you try to:

    pip install pip install git+https://github.com/zeehio/parmap.git@fix-23

And try if your code works?

**Comment by RealPolitiX** [comment]
Great, just tested, and it works now! Thanks @zeehio

**Comment by zeehio** [comment]
Just merged! Thanks!
