### ISSUE TITLE
how about add `tqdm.notebook` support?

### ISSUE THREAD

**Issue by wldh-g** [zeehio/parmap#25]
In jupyter notebook, just `tqdm` makes the progress bar printed repeatedly.

![image](https://user-images.githubusercontent.com/22350783/133944588-ce0e6140-060b-49b1-ae97-e69090c9627a.png)

This can be resolved by using `tqdm.auto` instead of `tqdm`.

So [this line](https://github.com/zeehio/parmap/blob/master/parmap/parmap.py#L79) can be modified as below:

```python
import tqdm.auto as tqdm
```

how do you think about this?

thanks

**Comment by zeehio** [comment]
Thanks!
