### ISSUE TITLE
Description and unit for the progress bar

### ISSUE THREAD

**Issue by kaparoo** [zeehio/parmap#28]
Is there a way to set the description or unit of the progress bar when pm_pbar is True?

If not, I think it is helpful to add keyword arguments like `pm_pbar_desc`, and `pm_pbar_unit` to support such features.

**Comment by zeehio** [comment]
I am sorry, I am not that familiar with progress bar options. I'm using the tqdm package. What would you expect the description and units do? Do you mean some text to be shown at the left and some postfix at the right of the progress bar? Or some other thing? An example (with a screenshot if possible) would be helpful.

Currently, if you want to process a list of 200 elements, the progress bar will have 200 steps, that will be filled as the elements are processed.

**Comment by zeehio** [comment]
If you are comfortable with `tqdm.tqdm()` options I could make it so `pm_pbar` can be a dictionary instead of just `True` and the contents of that dictionary will be appended to the `tqdm.tqdm()` call, so you can pass any options from https://tqdm.github.io/docs/tqdm/#__init__ (including `desc` and `unit`). Would that work for you?

**Comment by kaparoo** [comment]
> If you are comfortable with `tqdm.tqdm()` options I could make it so `pm_pbar` can be a dictionary instead of just `True` and the contents of that dictionary will be appended to the `tqdm.tqdm()` call, so you can pass any options from https://tqdm.github.io/docs/tqdm/#__init__ (including `desc` and `unit`). Would that work for you?

That is what I really want!
Making `pm_pbar` to be a dictionary would be more useful rather than just adding `pm_pbar_desc` or `pm_pbar_unit`.
Thank you for your immediate and kind reply.

**Comment by zeehio** [comment]
Closed in #29

**Comment by zeehio** [comment]
Feel free to use parmap 1.6.0, already on pypi and soon on conda-forge

**Comment by kaparoo** [comment]
Nice work! Thanks 😁
