### ISSUE TITLE
[SPAM] lewismc, plz read this

### ISSUE THREAD

**Issue by jay-buuum** [zeehio/parmap#31]
hello lewismc. You may be busy, but,
you must check this
Someone's stealing your GitHub and use for scamming,
Several victims have already occurred.
You may damage soon. It's a very serious situation.

- Implement DELETE's for UPDATE's to metadata only ingestion #289
- fswatch service cannot interpret more than one artifact at a time #288

I put a photo of evidence as a comment on the issue, so please check it out.
And please reply to me as soon as possible.

ohjibeom@gmail.com/ or
objectofficial@naver.com

**Comment by lewismc** [comment]
This is spam and the user has been reported.
