### ISSUE TITLE
MemoryError on Exception

### ISSUE THREAD

**Issue by saddy001** [zeehio/parmap#5]
When using parmap.map(func, par_list, par1, par2, par3, par4) in a loop, a MemoryError can occur if there is an Exception thrown inside func, which is handled outside of func. The new threads are not closed correctly this way and thus parmap spawns more and more threads (loop) until the RAM is full. This was not an easy one to find ;-)

**Comment by zeehio** [comment]
Hi, thanks for reporting this issue. You are right.

I did some tests on my own and the issue seems now fixed. Could you try and test it in your code?
`pip install git+https://github.com/zeehio/parmap.git`

Unless you find any issue with this patch I will upload it to pypi in a few days.

Thanks again!

**Comment by saddy001** [comment]
The thread count keeps constant now. Thanks for your fast fix.

**Comment by zeehio** [comment]
Maybe you already know this, but just in case some piece of advice:

If you are using `parmap.map` in a loop like this:

```python
import parmap

for i in range(1000):
    par_list = create_list()
    par1 = create_par1()
    par2 = create_par2()
    parmap.map(func, par_list, par1, par2)
```
`parmap.map` will start (and close) subprocesses 1000 times. (On my laptop) the overhead of starting the subprocesses is of 0.07 seconds for each `parmap.map` call (so 0.07*1000 = 70 extra seconds in total in this case). This may be small compared to the cost of evaluating func, but sometimes it is worth to take care of creating and closing the multiprocessing pool only once outside the loop as follows:

```python
import multiprocessing
import parmap

try:
    pool = multiprocessing.Pool()
    for i in range(1000):
        par_list = create_list()
        par1 = create_par1()
        par2 = create_par2()
        parmap.map(func, par_list, par1, par2, pool=pool)
finally:
    pool.close()
    pool.join()
```

Unless you are going to benefit significantly, I would suggest not to make the code more complex. But if you see your computer struggles creating and deleting python subprocesses, then it may be a good idea to do that.

**Comment by saddy001** [comment]
Thanks for this, because I do have more than 1000 calls.

Regards,
