### ISSUE TITLE
Full stack trace

### ISSUE THREAD

**Issue by saddy001** [zeehio/parmap#7]
It would be nice to get the full stack trace shown in error case. At the moment one can only only see a truncated one:

```
...
    res = parmap.map(func, list, *args, pool=pool)
  File "/usr/local/lib/python2.7/dist-packages/parmap.py", line 147, in map
    chunksize)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
[ Missing Part ]
ValueError: continuous format is not supported
```

**Comment by zeehio** [comment]
This is an issue with `multiprocessing`, that has been fixed on Python-3.4.
See http://bugs.python.org/issue13831

Unfortunately I don't have time to provide to work on a solution to a problem that has already been solved in a new python version. I can review a patch for parmap if you want to write it, though.
