### ISSUE TITLE
python multiprocessing with iterable and multiple arguments

### ISSUE THREAD

**Issue by dineshbvadhia** [zeehio/parmap#9]
http://stackoverflow.com/questions/43217901/python-multiprocessing-with-iterable-and-multiple-arguments

You might be interested in the above question on Stackoverflow. I tried parmap with 
```
z = parmap.map(func, iterable, args)
print(z)
```
with the result:

`['a this that other', 'b this that other', 'c this that other', 'd this that other', 'e this that other', 'f this that other', 'g this that other', 'h this that other']`

but should be: 

`['abc this that other', 'bcd this that other', 'cde this that other', 'def this that other', 'efg this that other', 'fgh this that other', 'ghi this that other', 'hij this that other']
`

**Comment by zeehio** [comment]
The code in the question seems wrong. `func` should expect a single item and not the whole iterable.

Instead of:

    def func(iterable, args):
        this, that, other = args[0], args[1], args[2]

        for s in iterable:
            return ' '.join([s, this, that, other])        


You may use:

    def func(item, args):
        this, that, other = args[0], args[1], args[2]
        return ' '.join([item, this, that, other])        

Or maybe I am missing the obvious and misunderstood the question.

**Comment by zeehio** [comment]
I would need to provide `parmap.imap` and `parmap.imap_unordered` though... pull requests are welcome

**Comment by dineshbvadhia** [comment]
Thank-you. parmap is very useful. 

One thing missing is dealing with python objects shared by all core processes. It could be a database, numpy array, a data object provided by an imported module and so on.

Is there a way to deal with this?

**Comment by zeehio** [comment]
In a general way I don't think so. The Global Interpreter Lock prevents us from freely sharing python objects between threads.

Here is more info about this that may work for you in some cases http://stackoverflow.com/a/28862472/446149

There is limited documentation for sharing state but I have never used that feature, and it does not look general: https://docs.python.org/3/library/multiprocessing.html#sharing-state-between-processes

**Comment by dineshbvadhia** [comment]
Yep, agree. Tried a number of methods but no luck. Thanks!
